name: Run My Crypto Engine

on:
  workflow_dispatch: # This adds a button so you can run it manually

jobs:
  run-script:
    runs-on: ubuntu-latest
    
    steps:
      - name: Get my code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install my libraries
        run: pip install -r requirements.txt

      - name: Run my script
        env:
          ALERT_EMAIL_TO: ${{ secrets.ALERT_EMAIL_TO }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
        run: python crypto_signal_engine.py
